config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  get '/users/:id/profile' => 'users#profile'
  get '/users/new' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  # resources :sports It does both

  resources :sports do
    resources :teams, only: [:create, :new]
    resources :games
  end

  resources :teams do
    resources :games
  end

  resources :teams, only: [:show, :destroy, :edit, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :game_teams
  has_many :teams, through: :game_teams
end

app/models/game_team.rb
class GameTeam < ApplicationRecord
  belongs_to :team
  belongs_to :game
end

app/models/sport.rb
class Sport < ApplicationRecord
  has_many :teams
  has_many :game_teams, through: :teams, class_name: "GameTeam"
  has_many :games, through: :game_teams, class_name: "Game"

  validates :name, presence: true, uniqueness: true
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users
  has_many :users, through: :team_users
  belongs_to :team_captain, class_name: "User", foreign_key: "user_id"
  accepts_nested_attributes_for :team_captain
  has_many :game_teams
  has_many :games, through: :game_teams
  belongs_to :sport
  validates :name, uniqueness: true
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :team_users
  has_many :teams, through: :team_users
  has_many :games, through: :teams

  validates :username, :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    p params
    p "*"*88

    @team = Team.find(params[:team_id])
    p @team
    p "*"*88

    @games = @team.games
    p @games
    p "*"*88
  end

  def new
    @team = Team.find(params[:team_id])
    @game = @team.games.new
  end

  def create
    @team = Team.find(params[:team_id])
    @game = @team.games.new(game_params)

    if @game.save
      redirect_to team_games_path
    else
      render 'new'
    end
  end

  def show
    @game = Game.find(params[:team_id])
    @date = @game.date
    @location = @game.location
  end

  private

  def game_params
    params.require(:game).permit(:date,:location, :team_1, :team_2)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to "/users/#{current_user.id}/profile"
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to "/"
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  def index
    @sports = Sport.all
  end

  def new
    @sport = Sport.new
  end

  def create
    @sport = Sport.new(sport_params)

    if @sport.save
      redirect_to @sport
    else
      render 'new'
    end
  end

  def edit
    @sport = Sport.find(params[:id])
  end

  def show
    @sport = Sport.find(params[:id])
    @teams = @sport.teams
  end

  def update
    @sport = Sport.find(params[:id])
    if @sport.update(sport_params)
      redirect_to @sport
    else
      render "edit"
    end
  end

  private
    def sport_params
      params.require(:sport).permit(:name, :description)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :show_teams, only: [:show, :create]

  def new
    @sport = Sport.find(params[:sport_id])
    @team = Team.new
  end

  def create
    sport = Sport.find(params[:sport_id])
    # User becomes team captain but only when you call team.team_captain
    @team = current_user.teams.new({name: params[:team][:name], user_id: current_user.id, sport_id: sport.id})

    if @team.save
      @team.users.push(current_user)
      redirect_to @team
    else
      render 'new'
    end
  end

  def edit
    @team = Team.find(params[:id])
  end


  def update
    @team = Team.find(params[:id])
    @team.users.each do |user|
      if user.username != params[:team][:team_captain][:username]
        flash[:alert] = 'User not on team!'

        render "edit"
      else
        @user = User.find_by(username: params[:team][:team_captain][:username])
        if @user == nil
          @team.errors.add(:team_captain, "Nope.")
          render "edit"
        elsif @team.update(name: params[:team][:name], user_id: @user.id)
          redirect_to @team
        else
          render "edit"
        end
      end
    end
  end

  def destroy
    Team.find(params[:id]).destroy
    flash[:success] = "Team Deleted"
    redirect_to "/"


  end


  private

    def show_teams
      @team = Team.find(params[:id])
      @users = @team.users
      @games = @team.games

      # respond_to do |format|
      #     # format.js { render :file => "/views/teams/new.js.erb"}
      #     format.js {render 'new'}
      #     @users << current_user
      #     format.html { render 'show' }
      # end

      if request.xhr?
        @users << current_user
        render "show"
      end


    end


    def team_params
      params.require(:team).permit(:name , :user_id, :sport_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include TeamCaptainHelper
  def profile
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to "/users/#{@user.id}/profile"
    else
      flash[:danger] = "Error creating a new instance of yourself!"
      render 'new'
    end
  end

  private

  def user_params
     params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/add_user_helper.rb
module AddUserHelper
  def add_user
    p "~^" * 100
    p "something"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def logout
    session.clear
  end
end

app/helpers/sessions_helpers.rb
module SessionsHelper

  def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  def logout
    session.clear
  end
end

app/helpers/team_captain_helper.rb
module TeamCaptainHelper
  def team_captain?(user, team)
    if user == team.team_captain
      true
    else
      false
    end
  end
end

app/views/games/index.html.slim
h2 Games
- @games.each do |game|
  br
  =link_to "#{game.team_1} vs #{game.team_2}", team_game_path(@team, game)

app/views/games/new.html.slim
h1 Create a New Game
.add-games
  = bootstrap_form_for :game, url: team_games_path do |f|
    = f.datetime_local_field :date, :class => 'datepicker'
    / .col-sm-6
    /   .form-group
    /     #datetimepicker1.input-group.date
    /       input.form-control[name="date" type="text"]
    /       span.input-group-addon
    /         span.glyphicon.glyphicon-calendar
    / script[type="text/javascript"]
    /   |  $(function () { $('#datetimepicker1').datetimepicker(); });
    br
    = f.text_field :location
    br
    = f.text_field :team_1
    br
    = f.text_field :team_2
    br
    = f.submit
= link_to 'Back', team_path(@team)

app/views/games/show.html.slim
h3
  = @game.team_1
  |&nbsp; vs &nbsp;
  = @game.team_2

  h5
    p = @date.strftime("Game is scheduled on #{"%B-%d-%Y"}")

app/views/home/index.html.slim
-if flash[:success]
  =flash[:success]

=image_tag("logo.png")
p Welcome to the intramural league app. Sign up for a team to start playing intramural sports!

app/views/layouts/_flash.html.slim
- if alert
  p = alert

- if notice
  p = notice

app/views/layouts/_navbar.html.slim
- if current_user
   nav.navbar.navbar-default
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
         ul.nav.navbar-nav
            li/
            = link_to "Logout  ", :controller => 'sessions', :action => 'destroy'
            span.sr-only
               | (current)
            li/
            = link_to "  Profile  ", "/users/#{current_user.id}/profile"
            span.sr-only
               | (current)
            li/
            = link_to "  Sports",  "/sports"
            span.sr-only
               | (current)
            li/
            = link_to "Home", "/"
            span.sr-only
               | (current)
- else
   nav.navbar.navbar-default
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
         ul.nav.navbar-nav
            li/
            = link_to "Login  ", :controller => 'sessions', :action => 'new'
            span.sr-only
               | (current)
            li/
            = link_to "  Register",  "/users/new"
            span.sr-only
               | (current)
            li/
            = link_to "Home", "/"
            span.sr-only
               | (current)


/ - if current_user
/    span
/       = link_to "Logout  ", :controller => 'sessions', :action => 'destroy'
/       ||
/       = link_to "  Profile  ", "/users/#{current_user.id}/profile"
/       ||
/       = link_to "  Sports",  "/sports"
/ - else
/    span
/       .user-login
/          button.click-button
/             = link_to "Login  ", :controller => 'sessions', :action => 'new'
/       ||
/       .users-new
/          button.click-button
/             = link_to "  Create new User",  "/users/new"

app/views/layouts/application.html.slim
doctype html

html
  head
    title
      | TheLeague
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'

    link[href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css" rel="stylesheet" integrity="sha384-zF4BRsG/fLiTGfR9QL82DrilZxrwgY/+du4p/c7J72zZj+FLYq4zY00RylP9ZjiT" crossorigin="anonymous"]

    link[href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"]

    link[href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" crossorigin="anonymous"]


    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body.body

    = render "layouts/navbar"
    .container

      = yield

app/views/sports/edit.html.slim
h1 Edit = @sport.name
= bootstrap_form_for :sport, url: sport_path(@sport), method: :patch do |f|
  - if @sport && @sport.errors.any?
    h2
      = pluralize(@sport.errors.count, "error")
      |  prohibited this post from being saved:
    ul
      - @sport.errors.full_messages.each do |msg|
        li
          = msg

  = f.text_field :name, placeholder: "Name"
  br
  = f.text_field :description, placeholder: "Description"
  br
  = f.submit
= link_to 'Back', sports_path

app/views/sports/index.html.slim
- if current_user

  h1 Sport Categories
  br
  h4
    -@sports.each do |sport|
      ul
        li =link_to sport.name, sport
  br
  p =link_to "Create A New Sport", new_sport_path
- else
  h5 Please Log in to View Page

app/views/sports/new.html.slim
h1 Create a New Sport
= bootstrap_form_for :sport, url: sports_path do |f|
  - if @sport && @sport.errors.any?
    h2
      = pluralize(@sport.errors.count, "error")
      |  prohibited this post from being saved:
    ul
      - @sport.errors.full_messages.each do |msg|
        li
          = msg

  = f.text_field :name, placeholder: "Name"
  br
  = f.text_field :description, placeholder: "Description"
  br
  = f.submit
= link_to 'Back', sports_path

app/views/sports/show.html.slim
h1 = @sport.name

p = @sport.description

span
  = link_to "Back  ", sports_path
  ||
  = link_to "  Edit  ", edit_sport_path

br

h2 Teams
- @teams.each do |team|
  h4
    ul
      li =link_to team.name, team
br
h5 = link_to "Create A New Team!", new_sport_team_url(@sport)
h2
  = link_to "  Games", sport_games_path(@sport)

app/views/users/new.html.slim
.add-users
  = bootstrap_form_for(@user) do |f|
    = f.text_field :username
    br
    = f.email_field :email
    br
    = f.password_field :password
    br
    = f.submit

app/views/users/profile.html.slim
- if current_user.id == @user.id
  h1.user-name
    | Welcome #{@user.username}
  h4.user-email
    = @user.email
  br
  h2.user-teams
    | Teams
  h4.user-teams
    - @user.teams.each do |team|
      =link_to team
              = "#{team.name} "
      ||
      - if team_captain?(current_user, team)
          = link_to " Edit ", edit_team_path(team)
          ||
          = link_to "  Delete",team_path(team),method: :delete
          br
  br
  h2.user-games
    | Games
    h4
      - @user.games.each do |game|
        = game.team_1
        |&nbsp; vs &nbsp;
        = game.team_2
        br

- else
  h1.user-name
    | #{@user.username}
  h4.user-email
    = @user.email
  br
  h2.user-games
    | Games
    h4
      - @user.games.each do |game|
        = game.team_1
        |&nbsp; vs &nbsp;
        = game.team_2
        br
br
br
br